services:
  db:
#    image: postgres:16-alpine
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${TICKETEER_DB_PASSWORD}
    ports:
      - "5432:5432"