spring:
  application:
    name: Ticketeer
  http:
    serviceclient:
      default:
        base-url: 'http://localhost:3131/ticketvendor/api'
    clients:
      imperative:
        factory: jdk
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    # set TICKETEER_DB_PASSWORD in your environment, e.g., by running "export TICKETEER_DB_PASSWORD=..." in the command line
    password: ${TICKETEER_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging:
  level:
#   see https://thorben-janssen.com/hibernate-logging-guide
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

ticketeer:
  version: 1
  name: ${spring.application.name}
  description: Your one stop ticket shop!
  currency: EUR
  categories:
    - Music
    - Theater
    - Opera
    - Sport
    - Circus
    - and more!
  environment: Default
  vendor:
    enabled: true