spring:
  application:
    name: Ticketeer

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketeer_db
    username: ticketeer_user
    # set TICKETEER_DB_PASSWORD in your environment, e.g., by running "export TICKETEER_DB_PASSWORD=..." in the command line
    password: ${TICKETEER_DB_PASSWORD}

ticketeer:
  version: 1
  name: ${spring.application.name}
  description: Your one stop ticket shop!
  currency: EUR
  categories:
    - Music
    - Theater
    - Opera
    - Sport
    - Circus
    - and more!
  environment: Default
